baseurl = "http://lyndaoleary.com"
title = "Lynda O'Leary"
languageCode = "en-gb"
canonifyurls = true
builddrafts = true

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  author = "Lynda O'Leary"
  description = "System Engineer based in Galway."
  disqusShortname = "LOL"
